name: Format Code
on:
  pull_request:
    branches: [main]

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        directory: ["packages/app", "packages/docs", "packages/proxy"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ${{ matrix.directory }}/package-lock.json

      - name: Install package dependencies
        working-directory: ${{ matrix.directory }}
        run: npm install

      - name: Run format command
        working-directory: ${{ matrix.directory }}
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: auto-format"
